### ISSUE TITLE
Killing open, not yet retuned Promises at the end of Controller.

### ISSUE THREAD

**Issue by mantsak** [brikis98/ping-play#16]
I noticed a funny behaviour when hitting reload on the browser very fast.

The Promises take up to a second and when I hit reload faster, they get spooled in the background.
This is a normal behaviour, since the code is still working asynchronously to get those respoonses.

When I wait another 5 seconds for a new reload I receive all those spooled promises back in the new requested page. So, this last page contains not only the regular requested Pagelets, but also many Pagelets from previous (at that time incomplete) requests.

This might be a security issue, if another user receives responses who were originally intended for another user.

A solution might be to "kill" previous Promises at the beginning/end of the Controller, but this probably has to be request or user based.

I'm still watching the behaviour and implemented some logging with timestamps in the Controller to see what really happens.

**Comment by brikis98** [comment]
I'm not sure how to reproduce this. I hit refresh very quickly in my browser, but I only get the expected response back. I waited a few seconds and hit refresh again and got the same thing. 

Which sample app and controller are you testing? Can you provide a bit more detail about the exact repro steps? Thanks!

**Comment by mantsak** [comment]
This happens only with `PageletRenderOptions.ServerSide` in my application, never with `PageletRenderOptions.ClientSide`.

I can't reproduce it with the `/serverSideRendering` route and therefore I'm closing the comment again.

I probably messed up with the code too much and have many divs with the same name due to copying. If it happens after my cleanup, I will shoot a small screencast.
