### ISSUE TITLE
Escaping not working

### ISSUE THREAD

**Issue by jamesward** [brikis98/ping-play#24]
I'm not sure if it is a Java 8 or Scala 2.11 thing but the escaping doesn't work for me.  The dashes just become dashes.
```
scala> "asdf-asdf".replaceAll("-", "\u002d")
res2: String = asdf-asdf
```

Here is my fixed Pagelet implementation that seems to work:
```scala
case class HtmlStreamPagelet(id: String, streamFuture: Future[HtmlStream]) extends Pagelet {
  override def renderServerSide(implicit ec: ExecutionContext): HtmlStream = {
    throw new UnsupportedOperationException(s"Server-side rendering is not supported for ${getClass.getName}")
  }

  override def renderClientSide(implicit ec: ExecutionContext): HtmlStream = {
    val wrapperStreamFuture = streamFuture.map { stream =>
      val escapedEnumerator = stream.enumerator.map { html =>
        Html(html.body.replaceAllLiterally("--", "\\u002d\\u002d"))
      }
      views.stream.pageletClientSide(HtmlStream.fromHtmlEnumerator(escapedEnumerator), id, PageletContentType.html)
    }
    HtmlStream.flatten(wrapperStreamFuture)
  }
}
```

**Comment by brikis98** [comment]
Are you sure it's not working? IIRC, the terminal will render `\u002d` as a dash...

**Comment by jamesward** [comment]
Yeah, it definitely wasn't working but it could be due to how I am trying to create an `HtmlStreamPagelet`.  Notice that I created a new `views.stream.pageletClientSide` template.

**Comment by brikis98** [comment]
What was the symptom that you were seeing?

BTW, the terminal definitely displays that unicode escape as a dash. Check out this slightly modified version:

```
scala> "asdf--asdf".replaceAll("--", "\u002d")
res3: String = asdf-asdf
```

**Comment by jamesward** [comment]
The content inside the `<code><!-- --></code>` was not being escaped.  Or it didn't appear to be because maybe the browser was rendering the unicode too.  Once I added the extra `\` to the escaping everything worked as expected and I could see the escaped content in the browser.

**Comment by brikis98** [comment]
Was that causing any problems in your code? Did you try include a `--></code>` in your data to see if it escapes the comment and code tags?

**Comment by brikis98** [comment]
Never mind, just created a case to repro this myself, and you're right, escaping is broken. Fix coming.

**Comment by jamesward** [comment]
Thanks @brikis98!

**Comment by brikis98** [comment]
Publishing version 0.13 now. Should be available in a few minutes. Let me know if it works for you.

**Comment by jamesward** [comment]
Thanks for the quick response!
