### ISSUE TITLE
install ping-play

### ISSUE THREAD

**Issue by shacoshe** [brikis98/ping-play#26]
hey, 
i want to install ping-play on a new play project, i added this to my SBT 

//ping-play BIG PIPE
libraryDependencies += "com.ybrikman.ping" %% "big-pipe" % "0.0.13"

TwirlKeys.templateFormats ++= Map("stream" -> "com.ybrikman.ping.scalaapi.bigpipe.HtmlStreamFormat")
TwirlKeys.templateImports ++= Vector("com.ybrikman.ping.scalaapi.bigpipe.HtmlStream", "com.ybrikman.ping.scalaapi.bigpipe._")
//END BIG-PIPE

activator compile
then
activator eclipse

but eclipse can't find any of the big pipe files.
please help .

also where can i find the bagpipe.js file ?

**Comment by brikis98** [comment]
Did you have activator (i.e., the SBT shell) running in the background after you added the dependency (so you just ran the `compile` command) or did you restart it (so you exited the shell and ran `activator compile`)?

I haven't used Eclipse in a long time, so I'm not sure how to debug it, but here's an experiment to see if the ping-play dependency is being pulled in correctly: create a Scala class anywhere in the project and import `com.ybrikman.ping.scalaapi.bigpipe.BigPipe`. If the code compiles, then the dependencies are being pulled in correctly, at least by the actual app. 

To add `big-pipe.js` to your project, just add the following line in your templates:

```
<script src="/assets/com/ybrikman/ping/big-pipe.js"></script>
```

The source for `big-pipe.js` is [here](https://github.com/brikis98/ping-play/blob/master/big-pipe/src/main/resources/public/com/ybrikman/ping/big-pipe.js).

**Comment by shacoshe** [comment]
i just run the "activator compile" command.
i placed  "import com.ybrikman.ping.scalaapi.bigpipe.BigPipe" in my Application.java, and my application compiles
but when i am adding "FakeServiceClient" i am getting this error

```
[error] ... project path..../app/controllers/Application.java:9: package helper does not exist
[error] helper.FakeServiceClient
[error] ... project path..../app/controllers/Application.java:12: cannot find symbol
[error]   symbol:   class FakeServiceClient
[error]   location: class controllers.Application
[error] FakeServiceClient
```

this is my src

```javascript
import javax.inject.Inject;

import play.mvc.Controller;
import play.mvc.Result;
import views.html.index;
import com.ybrikman.ping.scalaapi.bigpipe.BigPipe;
import helper.FakeServiceClient;

public class Application extends Controller {
	private final FakeServiceClient serviceClient;
	
	@Inject
	public Application(FakeServiceClient serviceClient) {
		this.serviceClient = serviceClient;
	}
	  
    public Result index() {
        return ok(index.render("Your new application is ready."));
    }

}
```

**Comment by brikis98** [comment]
`FakeServiceClient` is part of the sample code. It is (intentionally) not exported as part of the ping-play jar as most users have real clients to use instead. Probably the easiest way to use it is to just copy the code into your project.

**Comment by shacoshe** [comment]
thanks for the direction.
its more clear to me now :)

**Comment by brikis98** [comment]
No problem. I'll close the issue for now, but feel free to open others if you hit other problems.
