### ISSUE TITLE
get /sample-app-common/src/main/scala/data in Java ?

### ISSUE THREAD

**Issue by shacoshe** [brikis98/ping-play#27]
hi, i want to learn more about ping-play, so i want to place sample-app-common from the example inside my java application, since i don't have experience in scala.
i am a bit struggling with the conversion, is it possible to have also a java version ?

thanks

**Comment by brikis98** [comment]
See [sample-app-java](https://github.com/brikis98/ping-play/tree/master/sample-app-java) for a sample app written in Java.

**Comment by shacoshe** [comment]
hey, thanks.
i was referring to the common files here
https://github.com/brikis98/ping-play/tree/master/sample-app-common/src/main/scala/data

**Comment by brikis98** [comment]
Ah, that code is intentionally in a single place to try to reduce duplication. I'm not sure I'd want to convert it to Java and have to maintain both separately...

**Comment by shacoshe** [comment]
hmmm.... i understand :-)
it will be more easy for me, as one that don't know scala.
i have a bit of difficulties converting to java.

**Comment by brikis98** [comment]
What specifically are you struggling with?

**Comment by shacoshe** [comment]
FutureUtil has lots of errors when i am trying to convert it, like he can't recognize "Feature", even when he is ok with the import "import scala.concurrent.Future;".  i can't get the "timeout" method signature right... after trying to convert to java, the first and last methods results the same signature.

i don't know how to convert "Response" to java. since i am not a scala developer. 
i can guess "case class Response(id: String, delay: Long)" 
means
public class Response {
	
	private String m_id;
	private Long m_delay;
	
	public Response(String id, Long delay) {
		m_id    = id;
		m_delay = delay;
	}
}

as for 
object Response {
  implicit val responseWrites = Json.writes[Response]
} 

i have no idea, :) well ill have to learn scala for that

**Comment by brikis98** [comment]
First, just to confirm, are you converting all of this stuff as a learning project? Because if you're using ping-play for a real-world use case, you don't need any of the code from the sample apps; you would swap them out with libraries that do real work, such as calling an actual remote service instead of using `FutureUtil`, which just returns fixed data.

That said, there are a quite a few issues with your conversion.

First, `Future` should typically only be used with Scala code. For Java code, you should be using `Promise`. The Java sample app I linked earlier does exactly that.

Second, a `case class` is just (wonderful) syntactic sugar for a standard Java POJO, with auto generated getters, setters, equals, hashCode, and lots of other goodies. The rough equivalent of the `Response` class would be something like (with most of the goodies omitted, since you probably don't need them for a simple example):

```java
public class Response {
  public final String id;
  public final long delay;

  public Response(String id, long delay) {
    this.id = id;
    this.delay = delay;
  }
```

Finally, the `Json.writes` bit is the way Play does JSON serialization for Scala apps. For Java apps, it's done differently: https://playframework.com/documentation/2.4.x/JavaJsonActions

**Comment by shacoshe** [comment]
thank for the answers, and the time, i want it for a real project. 
so i guess for a real project i just have to 
replace this 
,,,
    F.Promise<Response> profilePromise = serviceClient.fakeRemoteCallMedium("profile")
,,,
With calling some other entry in the controller, and get the result as a promise object.

**Comment by brikis98** [comment]
Yes. For example, you could use [Play's Web Services Client](https://playframework.com/documentation/2.4.x/JavaWS):

```java
F.Promise<WSResponse> examplePromise = WS.url("http://www.example.com").get()
```

**Comment by shacoshe** [comment]
thanks for the response.  i am trying to convert some other entry to piglet, can you help me please
i am trying something much simples

,,,
public class Application extends Controller {

    public Result foo() {
        return ok("Got request " + request() + "!");
    }
    
    public Result index() {
    	
    	Promise<Result> promiseFoo = Promise.promise(new F.Function0<Result>() {
			@Override
            public Result apply() throws Throwable {
				return foo();
			}
		});
		
    	Pagelet profile = new HtmlPagelet("profile", promiseFoo.map(views.html.foo));
    	
        BigPipe bigPipe = new BigPipe(PageletRenderOptions.ClientSide, profile);
        return ok(HtmlStreamHelper.toChunks(views.stream.application.apply(bigPipe, profile)));
    }
    
}

,,,

**Comment by brikis98** [comment]
And what happens when you do that?

**Comment by shacoshe** [comment]
(inside eclipse)
```views.html.foo``` cannot be resolved 
also 
```views.stream``` cannot be resolved 

i think i am missing something :)

**Comment by brikis98** [comment]
In your example, you used `views.stream.application`. This is referencing a file `application.scala.stream`. Do you have such a file?

If you're using `views.html.foo`, then you would need an `application.scala.html`.

**Comment by shacoshe** [comment]
in my example i was trying to stick to the WithBigPipe example as possible
so i 'kind of' trying to replace the template and the controller names with mine, which docent make sense. 
i don't have ```application.scala.stream```, i called it same as in the example. just replaces ```withBigPipe``` with ```application```

this is what i am asking, how to do this right, i will say that ill trying to stick with java as much as possible

**Comment by shacoshe** [comment]
thanks
